idm:
  realm-name: "marketplace"
  server-url: "http://localhost:8079"
  client-id: "idm-client"
  client-secret: "0mQ9NcffKRJ6043JmDj4YDsOUguRNIJr"
  admin-username: "idm-admin"
  admin-password: "admin"
  pool-size: 10

default:
  security:
    oauth-client-registration-id: keycloak
  authorization-header-name: Authorization
  bearer-token-prefix: Bearer

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: app-service
            client-secret: TltbhY1HSvNczFkrqRBVAjhvwKLhpXB7
        provider:
          keycloak:
            token-uri: http://localhost:8079/realms/marketplace/protocol/openid-connect/token
