idm:
  realm-name: "marketplace"
  server-url: "http://localhost:8079"
  client-id: "idm-client"
  client-secret: "0mQ9NcffKRJ6043JmDj4YDsOUguRNIJr"
  admin-username: "idm-admin"
  admin-password: "admin"
  pool-size: 10

feign:
  oauth2:
    enabled: true

spring:
  security:
    oauth2:
      client:
        registration:
          COMPANY-SERVICE:
            authorization-grant-type: client_credentials
            client-id: app-service
            client-secret: TltbhY1HSvNczFkrqRBVAjhvwKLhpXB7
        provider:
          COMPANY-SERVICE:
            token-uri: http://localhost:8079/realms/marketplace/protocol/openid-connect/token
