spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8079/realms/marketplace
      client:
        registration:
          COMPANY-SERVICE:
            authorization-grant-type: client_credentials
            client-id: app-service
            client-secret: f4tvbpZSzkh9zXARBUjqu5QbbgjwJ1Py
        provider:
          COMPANY-SERVICE:
            token-uri: http://localhost:8079/realms/marketplace/protocol/openid-connect/token

feign:
  oauth2:
    enabled: true

default:
  page:
    size: 20
  role: MANAGER
  role-prefix: ROLE_
  jwt-realm-access-claim: realm_access
  jwt-roles-claim: roles

idm:
  realm-name: "marketplace"
  server-url: "http://localhost:8079"
  client-id: "idm-client"
  client-secret: "VuigehDFK0oiZ8f4yzeqoV3EWK6xC4ol"
  admin-username: "idm-admin"
  admin-password: "admin"
  pool-size: 10

exception:
  message:
    sessionFactoryInitFail: "Initialization of SessionFactory failed"
    categoryNotFound: "Category entity with id=%s is not present."
    itemNotFound: "Item entity with uuid=%s is not present."
    positionNotFound: "Position entity with id=%s is not found."
    userNotFound: "User entity with uuid=%s is not found."
    invalidCreatedBetweenFilter: "Filter 'created' = %s is invalid"
    nonUniqueUser: "User with such email %s or such username %s already exists"
    itemVersionsMismatch: "Provided item version does not match with the one in the database"
    positionVersionsMismatch: "Provided position version does not match with the one in the database"
    noItemVersionProvided: "No version for item with id %s was provided"
    userPasswordAbsent: "Could not update user as password is not present."
