spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "{KEYCLOAK_URI:http://localhost:8080}/realms/marketplace"

default:
  page:
    size: 20
  role: MANAGER
  role-prefix: ROLE_
  jwt-realm-access-claim: realm_access
  jwt-roles-claim: roles

exception:
  message:
    sessionFactoryInitFail: "Initialization of SessionFactory failed"
    companyNotFound: "Company entity with id=%s is not present."
    companyEmailTaken: "Company with email %s already exists"
