spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${KEYCLOAK_URI:http://localhost:8080}/realms/marketplace"
reactive-feign:
  http-client:
    read-timeout: 3000
    write-timeout: 3000
    connect-timeout: 3000
    response-timeout: 3000
  oauth2:
    client:
      registration:
        USER-SERVICE:
          authorization-grant-type: client_credentials
          client-id: position-service
          client-secret: "{cipher}AQBnsjYlC775ZGbgWfe1nGXAoPA9/G4NQ5M74iRgZlaLI5u3zcj6VqGjX7eD6BG/nYh5J4UXwt8XWHQikECfAc3+ufZSpeHeNq0JLHnrZ62xR7h1TJCiBBb8DQptSbc8d/91aJxZozlfa7er+w1zqGqjeGD+p5uK9EV3YBnV15+wHgnTosjpylMpAoV6drdkwOlFc8j6SN61Ynm7O+fwz+XNybZO08F87Fmz+6KbrULLV+G9ZG4o61ZhVhhD6AMJYcnahd+aaIABDGerwzG2inYwpetbD5i7IKpqBseUqlTvdU0Qc9YRsMT6SjG4IgqbnNDcSCLgG4UQVXyn8v5hvN+CkoSruGpyxka/IpUs4hweRaIFsWasiSQablB0lPM02vjF4n1DJK4pQjrtUi4jU3WZKXc7gkYtK5I5xhA7JauNBA=="
      provider:
        USER-SERVICE:
          token-uri: "${KEYCLOAK_URI:http://localhost:8080}/realms/marketplace/protocol/openid-connect/token"

reactive-feign-clients:
  user-client:
    name: USER-SERVICE
    url: "${USER_SERVICE_URL:}"
    path: "/api/v1/users"

default:
  page:
    size: 20
  role: MANAGER
  role-prefix: ROLE_
  jwt-realm-access-claim: realm_access
  jwt-roles-claim: roles

exception:
  message:
    sessionFactoryInitFail: "Initialization of SessionFactory failed"
    categoryNotFound: "Category entity with id=%s is not present."
    itemNotFound: "Item entity with uuid=%s is not present."
    positionNotFound: "Position entity with id=%s is not found."
    itemVersionsMismatch: "Provided item version does not match with the one in the database"
    noItemVersionProvided: "No version for item with id %s was provided"
    positionCreatedByAnotherPersonMessage: "Could not execute operation. Position was created by another person."
    creatorNotFound: "User who created this position is no longer present."
