spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${KEYCLOAK_URI:http://localhost:8080}/realms/marketplace"
      client:
        registration:
          USER-SERVICE:
            authorization-grant-type: client_credentials
            client-id: position-service
            client-secret: "{cipher}AQAPW+pWuZpZFirFApHlAPsRt5QeNjOlIb594Mi2ZntVcxnR9EixDqVvVocBGFwDqPj6m4Ge164SN9St7DG6HbmAuR7s45TY5KgxMWr7xympaUyTz5S3948eWYR+ZkpnMlog46GwPLI/CRe0K+0WChpZCXifSdwNaH3pbHQZbYBUvNeddpusb/kbO477p+jQuSXXziDPAt6V2JoQIsD0FmkAx3Heoe+JcKnobol8pzBuIgn1Bi80IlYlwvZ5ZsKWcWNI6lqEbfo0zot1rSbCrOZukc7EOPFEdiKg3P2f/GYNASv6uCMnFcMoeAMYItfYBz+6LBOQpCQOnfrTWbujd0+R5KmiBcoRbQwYLAhQxUivCbjdt7lQnokjQPuXKT39LWihmEo3pIvkcdyNOCCy+ksH1+7Rlu6qGDAimm6AhWUTsw=="
          COMPANY-SERVICE:
            authorization-grant-type: client_credentials
            client-id: position-service
            client-secret: "{cipher}AQAPW+pWuZpZFirFApHlAPsRt5QeNjOlIb594Mi2ZntVcxnR9EixDqVvVocBGFwDqPj6m4Ge164SN9St7DG6HbmAuR7s45TY5KgxMWr7xympaUyTz5S3948eWYR+ZkpnMlog46GwPLI/CRe0K+0WChpZCXifSdwNaH3pbHQZbYBUvNeddpusb/kbO477p+jQuSXXziDPAt6V2JoQIsD0FmkAx3Heoe+JcKnobol8pzBuIgn1Bi80IlYlwvZ5ZsKWcWNI6lqEbfo0zot1rSbCrOZukc7EOPFEdiKg3P2f/GYNASv6uCMnFcMoeAMYItfYBz+6LBOQpCQOnfrTWbujd0+R5KmiBcoRbQwYLAhQxUivCbjdt7lQnokjQPuXKT39LWihmEo3pIvkcdyNOCCy+ksH1+7Rlu6qGDAimm6AhWUTsw=="
        provider:
          USER-SERVICE:
            token-uri: "${KEYCLOAK_URI:http://localhost:8080}/realms/marketplace/protocol/openid-connect/token"
          COMPANY-SERVICE:
            token-uri: "${KEYCLOAK_URI:http://localhost:8080}/realms/marketplace/protocol/openid-connect/token"

feign:
  oauth2:
    enabled: true

default:
  page:
    size: 20
  role: MANAGER
  role-prefix: ROLE_
  jwt-realm-access-claim: realm_access
  jwt-roles-claim: roles

exception:
  message:
    sessionFactoryInitFail: "Initialization of SessionFactory failed"
    categoryNotFound: "Category entity with id=%s is not present."
    itemNotFound: "Item entity with uuid=%s is not present."
    positionNotFound: "Position entity with id=%s is not found."
    itemVersionsMismatch: "Provided item version does not match with the one in the database"
    noItemVersionProvided: "No version for item with id %s was provided"
    positionCreatedByAnotherPersonMessage: "Could not execute operation. Position was created by another person."
