spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${KEYCLOAK_URI:http://localhost:8080}/realms/marketplace"
      client:
        registration:
          CLIENT-SERVICES:
            authorization-grant-type: client_credentials
            client-id: user-transaction-service
            client-secret: "{cipher}AQAxrQ8L4wZBMMDurshYx+LMbtjKevhRLeGlJWVjy2lz5HX0ZS0VxTB0BAeetrAypLaWuQbq97vKV8GFyxafEFbFDrOpa3UiJHdDiZkfHUbE+lR0ohOpBtNMuzJ4DWjJtyocPOXF6Vp3bHLI+33f448uGsMdkwK2s8RNX3TV60MSZujK3e4cACMYsIL1+VnO6P2Wxr2mcsrzN4FjamVFfiYdU9mQYWIH/Fr1XHDQuFZNrcl3q3md4ByLJn3sfoBfLeZOOL87n4SReI0ofsEjXV9w2N4gBWUck6D2hfdUknuaYaCJrEp4O+VdASW2Tyxeibg2ubFSlNePSsW+iLXVsRq9zznL6P68b5JhEsS4rQldNHfuZEZv951B4neImgiwF0RDQuJf3ZBon2QJ7e0/1KFc5HoKsAJbm7zugk8g1iy7dQ=="
        provider:
          CLIENT-SERVICES:
            token-uri: "${KEYCLOAK_URI:http://localhost:8080}/realms/marketplace/protocol/openid-connect/token"

feign:
  oauth2:
    enabled: true
    clientRegistrationId: "CLIENT-SERVICES"

feign-clients:
  user-client:
    name: USER-SERVICE
    url: "${USER_SERVICE_URL:}"
    path: "/api/v1/users"
  position-client:
    name: POSITION-SERVICE
    url: "${POSITION_SERVICE_URL:}"
    path: "/api/v1/positions"

default:
  page:
    size: 20
  role: MANAGER
  role-prefix: ROLE_
  jwt-realm-access-claim: realm_access
  jwt-roles-claim: roles

exception:
  message:
    sessionFactoryInitFail: "Initialization of SessionFactory failed"
    insufficientItemsInStock: "Not enough items in stock for position with id=%s. Wanted amount=%s. Currently in stock=%s"
    insufficientOrderAmount: "Wanted amount=%s is less than position's(id=%s) minimum amount=%s"
