spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${KEYCLOAK_URI:http://localhost:8080}/realms/marketplace"
      client:
        registration:
          CLIENT-SERVICES:
            authorization-grant-type: client_credentials
            client-id: user-transaction-service
            client-secret: "{cipher}AQAiZJiL9h6BOXQiR4eSLA63M5en2vaBNqRmlckwgWC7XCOJxD6vnHWpSYY9k0Dk+HIbB0sBIrX6R7uPfQIXFg65atWNunBTnfgn5vp4Vk3gunx2LNO1h7eCr0+8chwrZYvAi1Ge2cjyZ8pXzRQGinrZ32qi7REt+YTuzSa3umOpHx/ZsyqWhzm8X5f+8pYmVTP78i/hnZ4/zPvYcXc3wqCgB+yHjOOUHxbquaE2BBSlYgue/givOUjT/nTtfGyEKrqVU3YRn3VFwJIuWX4dhYOyCjEMAE9qf8jXNjHDeHaJRrjyr/OnBaSbGRplCRjW64Q13rskAHEGct5+MXt7cyLLS+73aieRqkW6Pba/kGc0p16suADKnfCqBgfREO62EIN9zNc80VFRVG0tp20+E0wRw5hgq3WnSyZX41Ekqo4VaQ=="
        provider:
          CLIENT-SERVICES:
            token-uri: "${KEYCLOAK_URI:http://localhost:8080}/realms/marketplace/protocol/openid-connect/token"

feign:
  oauth2:
    enabled: true
    clientRegistrationId: "CLIENT-SERVICES"

feign-clients:
  user-client:
    name: USER-SERVICE
    url: "${USER_SERVICE_URL:}"
    path: "/api/v1/users"
  position-client:
    name: POSITION-SERVICE
    url: "${POSITION_SERVICE_URL:}"
    path: "/api/v1/positions"

default:
  page:
    size: 20
  role: MANAGER
  role-prefix: ROLE_
  jwt-realm-access-claim: realm_access
  jwt-roles-claim: roles

exception:
  message:
    sessionFactoryInitFail: "Initialization of SessionFactory failed"
    insufficientItemsInStock: "Not enough items in stock for position with id=%s. Wanted amount=%s. Currently in stock=%s"
    insufficientOrderAmount: "Wanted amount=%s is less than position's(id=%s) minimum amount=%s"
