spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${KEYCLOAK_URI:http://localhost:8080}/realms/marketplace"
      client:
        registration:
          CLIENT-SERVICES:
            authorization-grant-type: client_credentials
            client-id: user-transaction-service
            client-secret: "{cipher}AQAwNIbGA+1jXeIvLzq38Y8OQ/Cg7eBGdy0ir5tK/DTycLOhCk5ZJu9LTh43Hf1r1D7O3juUKpiPjXt2h/5gXpuhFF5Ks2Kw3p0cyiMR+91+C6Kq6Ap2d6+O/zVQbg0/OPsrI/anovji9yo4mOM467hIz/zyOasDrLFrRv/4QYGmEWC0Vo2XqxNAQQVLYunEwBaERoRqdPHtF5YDrNsO18fxrHfws2TeUQjVyAuIZJX2nqDT+hYPYRUr/sIyyZjzA98IBUeoWrGXSKRYELXWvnQeLj0BqlL1VNVL1dgNidYBpVXGQd4V18rT00KMBUtd8g02IkixVkwysbciAokrU9J6PmPbTRel2NztKhNHCcyzyk2dRqS863+f3LS3BGZPOaYyG7w5SVkj8F+J/tY5vNZAMFgXHu+b4S7hLo33s+moEA=="
        provider:
          CLIENT-SERVICES:
            token-uri: "${KEYCLOAK_URI:http://localhost:8080}/realms/marketplace/protocol/openid-connect/token"

feign:
  oauth2:
    enabled: true
    clientRegistrationId: "CLIENT-SERVICES"

feign-clients:
  user-client:
    name: USER-SERVICE
    url: "${USER_SERVICE_URL:}"
    path: "/api/v1/users"
  position-client:
    name: POSITION-SERVICE
    url: "${POSITION_SERVICE_URL:}"
    path: "/api/v1/positions"

default:
  page:
    size: 20
  role: MANAGER
  role-prefix: ROLE_
  jwt-realm-access-claim: realm_access
  jwt-roles-claim: roles

exception:
  message:
    sessionFactoryInitFail: "Initialization of SessionFactory failed"
    insufficientItemsInStock: "Not enough items in stock for position with id=%s. Wanted amount=%s. Currently in stock=%s"
    insufficientOrderAmount: "Wanted amount=%s is less than position's(id=%s) minimum amount=%s"
